Projet2Homechef/Projet2Homechef/Models/Prestation/Commande.cs
using System;
using System.ComponentModel.DataAnnotations.Schema;

namespace Projet2Homechef.Models.Prestation
{
    public class Commande
    {
        public int Id { get; set; }
        public Service Service { get; set; }
        public int Statut { get; set; }
        //Pour la demande de service
        public Villageois Villageois { get; set; }
        public string Demande { get; set; }
        [Column(TypeName = "date")]
        public DateTime DatePrestation { get; set; }
        //Pour monter le devis
        public string Devis { get; set; }
        public double Cout { get; set; }
        //Pour confirmer le devis
        public string ConfirmationDevis { get; set; }
        //Pour confirmer la prestation
        public string ConfirmationPrestation { get; set; }
        //Pour confirmer le retour du materiel
        public string ConfirmationRetour { get; set; }
        //Reclamation
        public int StatutReclamation { get; set; }
        public string ReclamationVillageois { get; set; }
        public string ReclamationChef { get; set; }
        public string ReponseGestionnaire { get; set; }

        /*public string MessageStatut(Statut)
        {
            return (message);
        }*/



    }
}


//Statut d'une presatation
/*
Statut = 1
Demande de Service Villageois
Avec date
Statut = 2
Creation du devis Chef
Statut = 3
Confirmation du devis Villageois
Accès aux informations entre Chef et villageois
Simulation de bloquage d'argent du Villageois
Statut = 4
Confirmation de la prestation Villageois
Simulation de bloquage d'argent du Villageois
Statut = 5
Confirmation du retour du materiel Chef

 */

Projet2Homechef/Projet2Homechef/Models/Prestation/Service.cs
using Microsoft.AspNetCore.Http;
using System.ComponentModel.DataAnnotations.Schema;

namespace Projet2Homechef.Models.Prestation
{
    public class Service
    {
        public int Id { get; set; }
        public string Titre { get; set; }
        public string Description { get; set; }
        public int Valider { get; set; }
        public Villageois Chef { get; set; }
        public string ImagePath { get; set; }
        [NotMapped]
        public IFormFile Image { get; set; }
    }
}

Projet2Homechef/Projet2Homechef/Controllers/PrestationController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Projet2Homechef.Models;
using Projet2Homechef.Models.Prestation;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;

namespace Projet2Homechef.Controllers
{
    public class PrestationController : Controller
    {
        private IWebHostEnvironment _webEnv;
        Dal dal = new Dal();
        public IActionResult Index()
        {
            return View();
        }

        public ActionResult PrestationChef()
        {
            var userId = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            int IdChef = Convert.ToInt32(userId);
            List<Villageois> listeDesVillageois = dal.ObtientTousLesVillageois();
            List<Service> listeDesServices = dal.ObtientTousLesServices();
            List<Commande> listeDesCommandes = dal.ObtientToutesLesCommandes().Where(i => i.Service.Chef.Id == IdChef).ToList();
            
            return View(listeDesCommandes);
        }


        public ActionResult PrestationVillageois()
        {
            var userId = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            int IdVillageois = Convert.ToInt32(userId);
            List<Villageois> listeDesVillageois = dal.ObtientTousLesVillageois();
            List<Service> listeDesServices = dal.ObtientTousLesServices();
            List<Commande> listeDesCommandes = dal.ObtientToutesLesCommandes().Where(i => i.Villageois.Id == IdVillageois).ToList();

            return View(listeDesCommandes);
        }

       /* public ActionResult DetailPrestation(int id)
        {
            
            List<Villageois> listeDesVillageois = dal.ObtientTousLesVillageois();
            List<Service> listeDesServices = dal.ObtientTousLesServices();
            List<Commande> listeDesCommandes = dal.ObtientToutesLesCommandes().Where(i => i.Id == id).ToList();

            return View(listeDesCommandes);
        }*/

        public ActionResult DetailPrestationVillageois(int id)
        {

            List<Villageois> listeDesVillageois = dal.ObtientTousLesVillageois();
            List<Service> listeDesServices = dal.ObtientTousLesServices();
            List<Commande> listeDesCommandes = dal.ObtientToutesLesCommandes().Where(i => i.Id == id).ToList();

            return View(listeDesCommandes);
        }

        public ActionResult DetailPrestationChef(int id)
        {

            List<Villageois> listeDesVillageois = dal.ObtientTousLesVillageois();
            List<Service> listeDesServices = dal.ObtientTousLesServices();
            List<Commande> listeDesCommandes = dal.ObtientToutesLesCommandes().Where(i => i.Id == id).ToList();

            return View(listeDesCommandes);
        }

        public ActionResult CreerPrestation(int id)
        {

            List<Villageois> listeDesVillageois = dal.ObtientTousLesVillageois();
            List<Service> listeDesServices = dal.ObtientTousLesServices();
            List<Commande> listeDesCommandes = dal.ObtientToutesLesCommandes().Where(i => i.Id == id).ToList();

            return View(listeDesCommandes);
        }

        [HttpPost]
        public ActionResult AjouterDemande(int Id, String Demande, DateTime DatePrestation)
        {
            
            dal.AjouterDemande(Id, Demande, DatePrestation);

            /*return Redirect("PrestationVillageois");*/
            return Redirect("/home");
        }

        [HttpPost]
        public ActionResult MonterDevis(int Id, String Devis, double Cout)
        {

            dal.MonterDevis(Id, Devis, Cout);
            return Redirect("/home");
            /*return Redirect("PrestationChef");*/
        }

        [HttpPost]
        public ActionResult ConfirmerDevis(int Id, String ConfirmationDevis)
        {

            dal.ConfirmerDevis(Id, ConfirmationDevis);
            return Redirect("/home");
            /*return Redirect("PrestationVillageois");*/
        }

        [HttpPost]
        public ActionResult ConfirmerPrestation(int Id, String ConfirmationPrestation)
        {

            dal.ConfirmationPrestation(Id, ConfirmationPrestation);
            return Redirect("/home");
            /*return Redirect("PrestationVillageois");*/
        }

        [HttpPost]
        public ActionResult ConfirmerRetour(int Id, String ConfirmationRetour)
        {

            dal.ConfirmerRetour(Id, ConfirmationRetour);
            return Redirect("/home");
            /*return Redirect("PrestationChef");*/
        }
    }
}

Projet2Homechef/Projet2Homechef/Views/Prestation/DetailPrestation.cshtml
@using Projet2Homechef.Models
@model List<Projet2Homechef.Models.Prestation.Commande>

@{
    ViewBag.Title = "DetailPrestation";
    Layout = "_LayoutHomeChefVuesSecondaires";
}

<h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">Vue sur la prestation</h2>
		<!-- Icon Divider-->
		<div class="divider-custom">
			<div class="divider-custom-line"></div>
			<div class="divider-custom-icon"><i class="fas fa-star"></i></div>
			<div class="divider-custom-line"></div>
		</div>
		<div class="row justify-content-start">

			@foreach(var commande in Model)
			{
				//les information du service, du chef et du villageois
					<div>Le service rendu:</div>    
					<div>@commande.Service.Titre</div>

					<div>Description:</div>    
					<div>@commande.Service.Description</div>
				
					<div>Proposer par: </div>    
					<div>@commande.Service.Chef.UserName</div>
				
					<div>@commande.Villageois.UserName</div>    
					<div>Vous a demandé</div>
				
		<img src="@commande.Service.ImagePath" width="400" height="400" />
		
		//Première Etape de validation de la demande du villageois
		if (@commande.Statut == 0)
		{
			
			<form action="/Prestation/AjouterDemande" method = "post"> 
				<input type="hidden" name="Id" value = @commande.Id />
				<input type="text" name="Demande" placeholder="Ce que vous souhaitez:" required=" "/>					
				<div>Prévu pour:</div>  
				<input type="datetime" name="DatePrestation" placeholder="..." required=""/>
				<input class="btn btn-success btn-xl" type="submit" value = "Envoyer Demande" />
			</form>
		}
		else
		{
			<div>@commande.Demande</div>    				
			<div>Prévu pour:</div>    
			<div>@commande.DatePrestation</div>
		}

		//Seconde Etape de l'établissement du devis du chef
		if (@commande.Statut == 1)
		{										
			<div>En attente du devis du chef</div>  				
		}
		else if (@commande.Statut >= 1)
		{
			<div>La proposition du chef:</div>    
			<div>@commande.Devis</div>
				
			<div>Pour le montant</div>    
			<div>@commande.Cout</div>
		}
		
		//Troisième Etape de l'acceptation du devis par le villageois
		if (@commande.Statut == 2)
		{										
			<form action="/Prestation/ConfirmerDevis" method = "post"> 	
				<input type="hidden" name="Id" value = @commande.Id />
				<input type="text" name="ConfirmationDevis" placeholder="Cela vous contient" required=" "/>															
			    <input class="btn btn-success btn-xl" type="submit" value = "Confirmer Devis" />		
			</form>
		}		
		else if (@commande.Statut >= 2)
		{
			<div>@commande.ConfirmationDevis</div>
		}
		
		//Quatrième Etape de le réception de la prestation par le villageois
		if (@commande.Statut == 3)
		{										
			<form action="/Prestation/ConfirmerPrestation" method = "post"> 
				<input type="hidden" name="Id" value = @commande.Id />
				<input type="text" name="ConfirmationPrestation" placeholder="Cela vous contient" required=" "/>															
			    <input class="btn btn-success btn-xl" type="submit" value = "Confirmer Prestation" />			
			</form>
		}		
		else if (@commande.Statut >= 3)
		{
			<div>@commande.ConfirmationPrestation</div>
		}

		//Cinquième Etape de la récupération du matériel du chef
		if (@commande.Statut == 4)
		{										
			<div>En attente de la confirmation du retour du matériel</div> 
		}		
		else if (@commande.Statut >= 4)
		{
			<div>@commande.ConfirmationRetour</div>
		}
		
          
       
			}
			

		</div>

Projet2Homechef/Projet2Homechef/Views/Prestation/DetailPrestationChef.cshtml
@using Projet2Homechef.Models
@model List<Projet2Homechef.Models.Prestation.Commande>



	@{
    ViewBag.Title = "DetailPrestationChef";
    Layout = "_LayoutHomeChefVuesSecondaires";

}
<!DOCTYPE html>
<html>


<head>
    <title>Detail Prestation</title>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="/css/csspresta.css">
</head>

<body>




    <img src="/images/sousmenu detailpresta.png" width="100%" id="imgtitre" />

    @foreach (var commande in Model)
    {
        <div class="divpresta1">
            <div class="divprestatitre">
                <h1 class=prestatitre1 >@commande.Service.Titre</h1>
            </div>
            <div class="divprestaimg">
                <img src="@commande.Service.ImagePath" width="100%" />
            </div>
            <div class="divprestaacteurs">
                <td> Service proposé par: </td>
                <td>@commande.Service.Chef.UserName</td>
                <br />
                <td>Demandé par :</td>
                <td>@commande.Villageois.UserName</td>
                <br />
                <td>Statut :</td>
                  @if (@commande.Statut==1)
                              {
                             <td>En attente du devis du chef</td>
                              }
                        @if(@commande.Statut==2)
                              {
                             <td>En attente de la confirmation du devis par le villageois</td>
                              }
                        @if(commande.Statut==3)
                              {
                             <td>En attente de la réception de la prestation par le villageois</td>
                              }
                        @if(@commande.Statut==4)
                              {
                             <td>Prestation complétée</td>
                              }
                         @if(@commande.Statut==5)
                              {
                             <td>Matériel rendu</td>
                              }
            </div>
        </div>

        <div class="divpresta2">
            <h2 class="prestatitre2">Description</h2>
            <p>@commande.Service.Description</p>
        </div>




        //Première Etape de validation de la demande du villageois

        if (@commande.Statut == 0)
        {
            <div class="divpresta3">
                <h2 class="prestatitre2">Demande</h2>
                <div>Le Villageois fait sa demande</div>
            </div>
        }
        else
        {
            <div class="divpresta3">
                <h2 class="prestatitre2">Demande</h2>
                <div>@commande.Demande</div>
                <div>Prévu pour:</div>
                <div>@commande.DatePrestation</div>
            </div>
        }


         


        //Seconde Etape de l'établissement du devis du chef
        if (@commande.Statut == 1)
        {
            <div class="divpresta4">
                <h2 class="prestatitre2">Devis</h2>
                <form action="/Prestation/MonterDevis" method = "post"> 
				<input type="hidden" name="Id" value = @commande.Id />
				 <textarea  name="Devis" placeholder="Ce que vous proposez" required=" "></textarea>					
				<td>Combien?</td>  
				<input type="number" name="Cout" placeholder="..." required=""/>					
			    <button class="btn btn-success btn" type="submit" value="Valider"> Envoyer Devis</button>			
			</form> 
            </div>
        }
        else if (@commande.Statut >= 1)
        {
            <div class="divpresta4">
                <h2 class="prestatitre2">Devis</h2>
                <div>La proposition du chef:</div>
                <div>@commande.Devis</div>

                <div>Pour le montant</div>
                <div>@commande.Cout</div>
            </div>
        }



        //Troisième Etape de l'acceptation du devis par le villageois
        if (@commande.Statut == 2)
        {
            <div class="divpresta5">
                <h2 class="prestatitre2">Confirmation devis</h2>
               <div>En attente de la confirmation du devis</div> 
            </div>
        }
        else if (@commande.Statut >= 2)
        {
            <div class="divpresta5">
                <h2 class="prestatitre2">Confirmation devis</h2>
                <div>@commande.ConfirmationDevis</div>
            </div>
        }



        //Quatrième Etape de le réception de la prestation par le villageois
        if (@commande.Statut == 3)
        {
            <div class="divpresta6">
                <h2 class="prestatitre2">Confirmation réalisation de la Prestation</h2>

               <div>En attente de la confirmation de la prestation par le Villageois</div>
            </div>
        }
        else if (@commande.Statut >= 3)
        {
            <div class="divpresta6">
                <h2 class="prestatitre2">Confirmation réalisation de la Prestation</h2>
                <div>@commande.ConfirmationPrestation</div>
            </div>
        }



        //Cinquième Etape de la récupération du matériel du chef
        if (@commande.Statut == 4)
        {
            <div class="divpresta7">
                <h2 class="prestatitre2">Confirmation du retour du Materiel</h2>
               <form action="/Prestation/ConfirmerRetourr" method = "post"> 	
				<input type="hidden" name="Id" value = @commande.Id />
                 <textarea  name="ConfirmationPrestation" placeholder="Commentaire sur la reception des biens" required=" "></textarea>																
			    <button class="btn btn-success btn" type="submit" value="Valider">Confirmation</button>			
			</form>
            </div>

        }
        else if (@commande.Statut >= 4)
        {
            <div class="divpresta7">
                <h2 class="prestatitre2">Confirmation du retour du Materiel</h2>
                <div>@commande.ConfirmationRetour</div>
            </div>
        }



    }




</body>
</html>

Projet2Homechef/Projet2Homechef/Views/Prestation/DetailPrestationVillageois.cshtml
@using Projet2Homechef.Models
@model List<Projet2Homechef.Models.Prestation.Commande>

@{
    ViewBag.Title = "DetailPrestationVillageois";
    Layout = "_LayoutHomeChefVuesSecondaires";

}
<!DOCTYPE html>
<html>


<head>
    <title>Detail Prestation</title>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="/css/csspresta.css">
</head>

<body>




    <img src="/images/sousmenu detailpresta.png" width="100%" id="imgtitre" />

    @foreach (var commande in Model)
    {
        <div class="divpresta1">
            <div class="divprestatitre">
                <h1 class=prestatitre1 >@commande.Service.Titre</h1>
            </div>
            <div class="divprestaimg">
                <img src="@commande.Service.ImagePath" width="100%" />
            </div>
            <div class="divprestaacteurs">
                <td> Service proposé par: </td>
                <td>@commande.Service.Chef.UserName</td>
                <br />
                <td>Demandé par :</td>
                <td>@commande.Villageois.UserName</td>
                <br />
                <td>Statut :</td>
                        @if (@commande.Statut==1)
                              {
                             <td>En attente du devis du chef</td>
                              }
                        @if(@commande.Statut==2)
                              {
                             <td>En attente de la confirmation du devis par le villageois</td>
                              }
                        @if(commande.Statut==3)
                              {
                             <td>En attente de la réception de la prestation par le villageois</td>
                              }
                        @if(@commande.Statut==4)
                              {
                             <td>Prestation complétée</td>
                              }
                         @if(@commande.Statut==5)
                              {
                             <td>Matériel rendu</td>
                              }

                
            </div>
        </div>

        <div class="divpresta2">
            <h2 class="prestatitre2">Description</h2>
            <p>@commande.Service.Description</p>
        </div>




        //Première Etape de validation de la demande du villageois

        if (@commande.Statut == 0)
        {
            <div class="divpresta3">
                <h2 class="prestatitre2">Demande</h2>
                <form action="/Prestation/AjouterDemande" method="post">
                    <input type="hidden" name="Id" value=@commande.Id />
                    <textarea  name="Demande" placeholder="Ce que vous souhaitez:" required=" "></textarea>
                    <div>Prévu pour:</div>
                    <input type="datetime" name="DatePrestation" placeholder="..." required="" />
                    <input class="btn btn-success btn" type="submit" value="Envoyer Demande" />
                </form>
            </div>
        }
        else
        {
            <div class="divpresta3">
                <h2 class="prestatitre2">Demande</h2>
                <div>@commande.Demande</div>
                <div>Prévu pour:</div>
                <div>@commande.DatePrestation</div>
            </div>
        }





        //Seconde Etape de l'établissement du devis du chef
        if (@commande.Statut == 1)
        {
            <div class="divpresta4">
                <h2 class="prestatitre2">Devis</h2>
                <div>En attente du devis du chef</div>
            </div>
        }
        else if (@commande.Statut >= 1)
        {
            <div class="divpresta4">
                <h2 class="prestatitre2">Devis</h2>
                <div>La proposition du chef:</div>
                <div>@commande.Devis</div>

                <div>Pour le montant</div>
                <div>@commande.Cout</div>
            </div>
        }



        //Troisième Etape de l'acceptation du devis par le villageois
        if (@commande.Statut == 2)
        {
            <div class="divpresta5">
                <h2 class="prestatitre2">Confirmation devis</h2>
                <form action="/Prestation/ConfirmerDevis" method="post">
                    <input type="hidden" name="Id" value=@commande.Id />
                   <textarea  name="ConfirmationDevis" placeholder="Cela vous convient ?" required=" "></textarea>
                   <input class="btn btn-success btn" type="submit" value="Confirmer Devis" />
                </form>
            </div>
        }
        else if (@commande.Statut >= 2)
        {
            <div class="divpresta5">
                <h2 class="prestatitre2">Confirmation devis</h2>
                <div>@commande.ConfirmationDevis</div>
            </div>
        }



        //Quatrième Etape de le réception de la prestation par le villageois
        if (@commande.Statut == 3)
        {
            <div class="divpresta6">
                <h2 class="prestatitre2">Prestationréalisée ?</h2>

                <form action="/Prestation/ConfirmerPrestation" method="post">
                    <input type="hidden" name="Id" value=@commande.Id />
                    <textarea  name="ConfirmationPrestation" placeholder="La prestation s'est-elle bien déroulée ?" required=" "></textarea>
                    <input class="btn btn-success btn" type="submit" value="Confirmer Prestation" />
                </form>
            </div>
        }
        else if (@commande.Statut >= 3)
        {
            <div class="divpresta6">
                <h2 class="prestatitre2">Prestationréalisée ?</h2>
                <div>@commande.ConfirmationPrestation</div>
            </div>
        }



        //Cinquième Etape de la récupération du matériel du chef
        if (@commande.Statut == 4)
        {
            <div class="divpresta7">
                <h2 class="prestatitre2">Confirmation du retour du Materiel</h2>
                <div class="textlabelpresta">En attente de la confirmation du retour du matériel</div>
            </div>

        }
        else if (@commande.Statut >= 4)
        {
            <div class="divpresta7">
                <h2 class="prestatitre2">Confirmation du retour du Materiel</h2>
                <div class="textlabelpresta">@commande.ConfirmationRetour</div>
            </div>
        }



    }




</body>
</html>

Projet2Homechef/Projet2Homechef/Views/Prestation/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Projet2Homechef/Projet2Homechef/Views/Prestation/IndexPrestationchefVillageois.cshtml
@using Projet2Homechef.Models
@model List<Projet2Homechef.Models.Prestation.Commande>

@{
    ViewBag.Title = "Mes Prestations";
    
}

<body>

   

</body>

Projet2Homechef/Projet2Homechef/Views/Prestation/PrestationChef.cshtml
@using Projet2Homechef.Models
@model List<Projet2Homechef.Models.Prestation.Commande>

@{
    ViewBag.Title = "PrestationChef";
	
}
<h2><img id ="imgTitre" src="/images/sousmenu presta.png"  /></h2>
        <div class="divider-custom">
			<h2>Mes services en cours</h2>
			
		</div>
<table class="styled-table">

      <tr>
          <th>Id</th>    
          <th>Titre</th>  
          <th>Description</th>
          <th>Client</th> 
          <th>   </th>
          
         
       </tr>
    @foreach(var commande in Model)
    {
         <tr>
          <td>@commande.Id</td>    
          <td>@commande.Service.Titre</td>
          <td>@commande.Service.Description</td>
          <td>@commande.Villageois.UserName</td>
          
          <td> <button1 class="btn btn-success btn" type="submit">@Html.ActionLink("Détail", "DetailPrestationChef", "Prestation",new{@id = @commande.Id}) </button1> </td>

      </tr>
      
  
      
    }
</table>

Projet2Homechef/Projet2Homechef/Views/Prestation/PrestationVillageois.cshtml
@using Projet2Homechef.Models
@model List<Projet2Homechef.Models.Prestation.Commande>

@{
    ViewBag.Title = "PrestationVillageois";
	
}

        <div class="divider-custom">
			<h2>Mes commandes en cours</h2>
			
		</div>
<table class="styled-table">

      <tr>
          <th>Id</th>    
          <th>Titre</th>  
          <th>Description</th>
          <th>Chef</th> 
          <th>   </th>
          
         
       </tr>
    @foreach(var commande in Model)
    {
         <tr>
          <td>@commande.Id</td>    
          <td>@commande.Service.Titre</td>
          <td>@commande.Service.Description</td>
          <td>@commande.Service.Chef.UserName</td>
          
          <td> <button1 class="btn btn-success btn" type="submit">@Html.ActionLink("Détail", "DetailPrestationChef", "Prestation",new{@id = @commande.Id}) </button1> </td>

      </tr>
      
  
      
    }
</table>

       