Projet2Homechef/Projet2Homechef/Models/Prestation/Service.cs
using Microsoft.AspNetCore.Http;
using System.ComponentModel.DataAnnotations.Schema;

namespace Projet2Homechef.Models.Prestation
{
    public class Service
    {
        public int Id { get; set; }
        public string Titre { get; set; }
        public string Description { get; set; }
        public int Valider { get; set; }
        public Villageois Chef { get; set; }
        public string ImagePath { get; set; }
        [NotMapped]
        public IFormFile Image { get; set; }
    }
}

Projet2Homechef/Projet2Homechef/Controllers/ServiceController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Projet2Homechef.Models;
using Projet2Homechef.Models.Prestation;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Claims;

namespace Projet2Homechef.Controllers
{
    
    public class ServiceController : Controller
    {
        private IWebHostEnvironment _webEnv;
        Dal dal = new Dal();
        public ServiceController(IWebHostEnvironment environment)
        {
            _webEnv = environment;
            
        }
        public ActionResult CreerService()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CreerService(Service service)
        {
            /*string uploads = Path.Combine(_webEnv.WebRootPath, "images");
            string filePath = Path.Combine(uploads, service.Image.FileName);
            using (Stream fileStream = new FileStream(filePath, FileMode.Create))
            {
                service.Image.CopyTo(fileStream);
            }
            
            var userId = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            int IdChef =Convert.ToInt32(userId);*/
            //dal.CreerService(service.Titre, service.Description, "/images/"+service.Image.FileName, IdChef);
            return Redirect("/home");
        }

        public ActionResult Index()
        {
            List<Service> listeDesServices = dal.ObtientTousLesServices().Where(v => v.Valider == 1).ToList();
            List<Villageois> listeDesVillageois = dal.ObtientTousLesVillageois();
            return View(listeDesServices);
        }

        public ActionResult CatalogueHomechef()
        {          
            List<Service> listeDesServices = dal.ObtientTousLesServices().Where(v => v.Valider == 1).ToList();
            List<Villageois> listeDesVillageois = dal.ObtientTousLesVillageois();
            return View(listeDesServices);
        }

        public ActionResult CatalogueHomechef2()
        {
            List<Service> listeDesServices = dal.ObtientTousLesServices().Where(v => v.Valider == 1).ToList();
            List<Villageois> listeDesVillageois = dal.ObtientTousLesVillageois();
            return View(listeDesServices);
        }

        public ActionResult CatalogueHomechef3()
        {
            List<Service> listeDesServices = dal.ObtientTousLesServices().Where(v => v.Valider == 1).ToList();
            List<Villageois> listeDesVillageois = dal.ObtientTousLesVillageois();
            return View(listeDesServices);
        }

        public ActionResult MonCatalogue()
        {
            var userId = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            int IdChef = Convert.ToInt32(userId);
            List<Villageois> listeDesVillageois = dal.ObtientTousLesVillageois();
            List<Service> listeDesServices = dal.ObtientTousLesServices().Where(i => i.Chef.Id == IdChef).ToList();           

            return View(listeDesServices);
        }

        public ActionResult MonCatalogue2()
        {
            var userId = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            int IdChef = Convert.ToInt32(userId);
            List<Villageois> listeDesVillageois = dal.ObtientTousLesVillageois();
            List<Service> listeDesServices = dal.ObtientTousLesServices().Where(i => i.Chef.Id == IdChef).ToList();

            return View(listeDesServices);
        }

        //Vers Prestation
        public ActionResult Demander(int idService)
        {
            var userId = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            int idVillageois = Convert.ToInt32(userId);
            dal.AjouterPrestation(idService, idVillageois);
            int idCommande = dal.ObtientIdCommande(0);
            return Redirect("/Prestation/DetailPrestationVillageois/"+idCommande);
        }

    }
}

Projet2Homechef/Projet2Homechef/Controllers/VillageoisController.cs
using Microsoft.AspNetCore.Mvc;
using Projet2Homechef.Models;
using Projet2Homechef.Models.Prestation;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;

namespace Projet2Homechef.Controllers
{
    public class VillageoisController : Controller
    {
        public IActionResult Villageois()

        {
            Dal dal = new Dal();
            var userId = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            Villageois villageoisConnected = dal.ObtientUnVillageois(Convert.ToInt32(userId));
            return View(villageoisConnected);
        }

        public IActionResult VillageoisServices()

        {
            Dal dal = new Dal();
            var userId = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            int userIdInt = Convert.ToInt32(userId);
            List<Villageois> listeDesVillageois = dal.ObtientTousLesVillageois().ToList();
            List<Service> listeDesServices = dal.ObtientTousLesServices().Where(v => v.Chef.Id == userIdInt).ToList();
            return View(listeDesServices);
        }

        public IActionResult DeleteService(int id)
        {
            Dal dal = new Dal();
            dal.SupprimerService(id);
            return RedirectToAction("VillageoisServices");
        }

        public IActionResult ModifierService(int id)
        {
            if (id != 0)
            {
                using (Dal dal = new Dal())
                {
                    Service service = dal.ObtientTousLesServices().Where(r => r.Id == id).FirstOrDefault();
                    if (service == null)
                    {
                        ViewData["message"] = "Ce service n'est pas dans la base";
                        return View("Error");
                    }
                    return View(service);
                }
            }
            return View("Error");
        }

        [HttpPost]
        public IActionResult ModifierService(int id, string Titre, string Description)
        {

            if (id != 0)
            {
                using (Dal dal = new Dal())
                {
                    var userId = User.FindFirst(ClaimTypes.NameIdentifier).Value;
                    dal.ModifierService(id, Titre, Description, Convert.ToInt32(userId));
                    return RedirectToAction("ModifierService", new { @id = id });
                }
            }
            else
            {
                ViewData["message"] = "ce service n'est pas dans la base";
                return View("Error");
            }
        }

    }
}

Projet2Homechef/Projet2Homechef/Views/Service/CatalogueHomechef.cshtml
@using Projet2Homechef.Models
@model List<Projet2Homechef.Models.Prestation.Service>

@{
    ViewBag.Title = "CatalogueHomechef";
    
}

<h2><img id ="imgTitre" src="/images/sousmenu catalog.png"  /></h2>
		
		<div class="row justify-content-start">

			@foreach(var service in Model)
			{
				
				
				
				<div class="card col-6 m-5" style="width: 18rem;">
					<div class="card-body d-flex flex-column justify-content-between">
                        <div>
                            <h5 class="card-title">@service.Titre</h5>
                            <div class="my-3">
                               
                            </div>
                            <img src="@service.ImagePath" width="200" height="200" />
                            
                            <p class="card-text">@service.Description</p>
							<p class="card-text">@service.Chef.UserName</p>

                        </div>
						
						<div>
   
							<td> <button1 class="btn btn-success btn-xl" type="submit">@Html.ActionLink("Demander", "Demander", "Service",  new {idService =@service.Id} ) </button1> </td>
                            

                        </div>
                        
						

					</div>
				</div>
			}
			

		</div>

Projet2Homechef/Projet2Homechef/Views/Service/CatalogueHomechef2.cshtml
@using Projet2Homechef.Models
@model List<Projet2Homechef.Models.Prestation.Service>

@{
    ViewBag.Title = "CatalogueHomechef";
    
}

<h2><img id ="imgTitre" src="/images/sousmenu catalog.png"  /></h2>
		
		<div class="row justify-content-start">

			@foreach(var service in Model)
			{
				
				<!-- -->
				
				<!--div class="card col-6 m-5" style="width: 18rem;"-->
				<div class="card col-6 m-5" style="width: 36rem;">
					<div class="card-body d-flex flex-column justify-content-between">  
                        <div>
                            <h5 class="card-title">@service.Titre</h5>
                            <div class="my-3">
                               
                            </div>
							<div class="row">
							<div class="col-lg-4 ms-auto">
								<img id="imgCard" src="@service.ImagePath" width="200" height="200" />
                            </div>
							<div class="col-lg-4 ms-auto">
								<p class="card-text">@service.Description</p>								
								<p class="card-text">Proposé par :</p>
								<p class="card-text">@service.Chef.UserName</p>
								<div id="right">
								<button1 class="btn btn-success btn-xl" type="submit">@Html.ActionLink("Demander", "Demander", "Service",  new {idService =@service.Id} ) </button1>
							</div>
							</div>
							</div>
                        </div>
						
						<div>
   
							<td>  </td>
                            

                        </div>
                        
						

					</div>
				</div>
			}
			

		</div>

		

Projet2Homechef/Projet2Homechef/Views/Service/CatalogueHomechef3.cshtml
@using Projet2Homechef.Models
@model List<Projet2Homechef.Models.Prestation.Service>

@{
    ViewBag.Title = "CatalogueHomechef";
    
}

<h2><img id ="imgTitre" src="/images/sousmenu catalog.png"  /></h2>
		
		<div class="row justify-content-start">

			@foreach(var service in Model)
			{
				
				<!-- -->
				
				<!--div class="card col-6 m-5" style="width: 18rem;"-->
				<div class="card col-6 m-5" style="width: 36rem;">
					<div class="card-body d-flex flex-column justify-content-between">  
                        <div>
                            <h5 class="card-title">@service.Titre</h5>
                            <div class="my-3">
                               
                            </div>
							<div class="row">
							<div class="col-lg-4 ms-auto">
								<img id="imgCard" src="@service.ImagePath" width="200" height="200" />
                            </div>
							<div class="col-lg-4 ms-auto">
								<p class="card-text">@service.Description</p>								
								<p class="card-text">Proposé par :</p>
								<p class="card-text">@service.Chef.UserName</p>
								<div id="right">
								<!--<button1 class="btn btn-success btn-xl" type="submit" href="#connexion">Connexion</button1>-->
							</div>
							</div>
							</div>
                        </div>
						
						<div>
   
							<td>  </td>
                            

                        </div>
                        
						

					</div>
				</div>
			}
			

		</div>

		@*<div class="row">
			<div class="col-lg-4 ms-auto"><p class="lead">Cette application a été conçue afin que vous votiez pour vos sejours favoris</p></div>
			<div class="col-lg-4 me-auto"><p class="lead">A la fin de chaque sondage, un sejour sera choisi.</p></div>
		</div>*@

Projet2Homechef/Projet2Homechef/Views/Service/CreerService.cshtml
@model Projet2Homechef.Models.Prestation.Service
@{
    ViewBag.Title = "CreerService";
    Layout = "_LayoutHomeChefVuesSecondaires";
}

<h3 class="titre">CreerService (Désactivé)</h3>

<div class="col-lg-8 col-xl-7">
    @using (Html.BeginForm("CreerService","Service",FormMethod.Post, new {enctype="multipart/form-data"}))
     {
        <div class="form-floating mb-3">
            @Html.TextBoxFor(model => model.Titre, new { @class = "form-control", placeholder = "Titre" })
            @Html.LabelFor(model => model.Titre)
            @Html.ValidationMessageFor(model => model.Titre)
        </div>
        <div class="form-floating mb-3">
            @Html.TextBoxFor(model => model.Description, new { @class = "form-control", placeholder = "Description" })
            @Html.LabelFor(model => model.Description)
            @Html.ValidationMessageFor(model => model.Description)
        </div>

        @Html.HiddenFor(model=>model.ImagePath)
                    <div class="d-flex flex-row my-3">
                        <div class="mb-3 d-flex">
                            <div>
                                <li>@Html.LabelFor(model => model.Image, new { id = "imageLabel", @style = "text-align:center;" })</li>
                                <li>@Html.TextBoxFor(model => model.Image, new { placeholder = "Description", @type = "file" })</li>

                            </div>
                        </div>
                        <div class="text-center">
                            
                        </div>
                    </div>
                        <!-- Submit Button-->
        <button class="btn btn-primary btn-xl" type="submit">Désactivé</button>
    }
</div>

Projet2Homechef/Projet2Homechef/Views/Service/Index.cshtml
@using Projet2Homechef.Models
@model List<Projet2Homechef.Models.Prestation.Service>

@{
    ViewBag.Title = "Index";
    Layout = "_LayoutHomeChefVuesSecondaires";
}

<h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">Service</h2>
		<!-- Icon Divider-->
		<div class="divider-custom">
			<div class="divider-custom-line"></div>
			<div class="divider-custom-icon"><i class="fas fa-star"></i></div>
			<div class="divider-custom-line"></div>
		</div>
		<div class="row justify-content-start">

			@foreach(var service in Model)
			{
				
				<div class="card col-6 m-5" style="width: 18rem;">
					<div class="card-body d-flex flex-column justify-content-between">
                        <div>
                            <h5 class="card-title">@service.Titre</h5>
                            <div class="my-3">
                               
                            </div>
                            <img src="@service.ImagePath" width="200" height="200" />
                            
                            <p class="card-text">@service.Description</p>
							<p class="card-text">@service.Chef.UserName</p>

                         </div>
	
					</div>
				</div>
			}
			<div class="col-4 m-5" style="width: 18rem;">
				<a href="/Service/CreerService">
					<svg xmlns="http://www.w3.org/2000/svg" width="160" height="160" fill="black" class="align-middle bi bi-plus" viewBox="0 0 16 16">
						<path class="plus" d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z" />
					</svg>
				</a>
			</div>

		</div>

Projet2Homechef/Projet2Homechef/Views/Service/MonCatalogue.cshtml
@using Projet2Homechef.Models
@model List<Projet2Homechef.Models.Prestation.Service>

@{
    ViewBag.Title = "MonCatalogue";

}

<h2><img id ="imgTitre" src="/images/sousmenu meservices.png"  /></h2>
		

		<div class="row justify-content-start">

			@foreach(var service in Model)
			{
				
				<div class="card col-6 m-5" style="width: 18rem;">
					<div class="card-body d-flex flex-column justify-content-between">
                        <div>
                            <h5 class="card-title">@service.Titre</h5>
                            <div class="my-3">
                               
                            </div>
                            <img src="@service.ImagePath" width="200" height="200" />
                            
                            <p class="card-text">@service.Description</p>
							<p class="card-text">@service.Valider</p>

                        </div>
			
                        
						

					</div>
				</div>
			}
			<div class="col-4 m-5" style="width: 18rem;">
				<a href="/Service/CreerService">
					<svg xmlns="http://www.w3.org/2000/svg" width="160" height="160" fill="black" class="align-middle bi bi-plus" viewBox="0 0 16 16">
						<path class="plus" d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z" />
					</svg>
				</a>
			</div>

		</div>

Projet2Homechef/Projet2Homechef/Views/Service/Moncatalogue2.cshtml
@using Projet2Homechef.Models
@model List<Projet2Homechef.Models.Prestation.Service>

@{
    ViewBag.Title = "CatalogueHomechef";
    
}

<h2><img id ="imgTitre" src="/images/sousmenu meservices.png"  /></h2>
		
		<div class="row justify-content-start">

			@foreach(var service in Model)
			{
				
				<!-- -->
				
				<!--div class="card col-6 m-5" style="width: 18rem;"-->
				<div class="card col-6 m-5" style="width: 36rem;">
					<div class="card-body d-flex flex-column justify-content-between">  
                        <div>
                            <h5 class="card-title">@service.Titre</h5>
                            <div class="my-3">
                               
                            </div>
							<div class="row">
							<div class="col-lg-4 ms-auto">
								<img id="imgCard" src="@service.ImagePath" width="200" height="200" />
                            </div>
							<div class="col-lg-4 ms-auto">
								<p class="card-text">@service.Description</p>								
								<p class="card-text">Proposé par :</p>
								<p class="card-text">@service.Chef.UserName</p>
								<div id="right">
								<td> <button1 class="btn btn-success btn-xl" type="submit">@Html.ActionLink("Modifier", "ModifierService", "Villageois",new{@id = @service.Id}) </button1> </td>
								<td> <button2 class="btn btn-danger btn-xl" type="submit">@Html.ActionLink("Supprimer", "DeleteService", "Villageois", new{@id = @service.Id})</button2> </td>
								</div>
							</div>
							</div>
                        </div>
						
						<div>

                        </div>                        						
					</div>
				</div>
			}
			<div class="col-4 m-5" style="width: 18rem;">
				<a href="/Service/CreerService">
					<svg xmlns="http://www.w3.org/2000/svg" width="160" height="160" fill="black" class="align-middle bi bi-plus" viewBox="0 0 16 16">
						<path class="plus" d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z" />
					</svg>
				</a>
			</div>

		</div>

		